### ISSUE TITLE
Feature Request with love by CrackedLix

### ISSUE THREAD

**Issue by kitovoi111** [min2222/Mins-Enchantments#2]
Hello. Today I won’t ask you to fix the Alex’s Caves mod, listen to this matter. I see you are simply EXCELLENT at porting mods, your work is TALENT.

How about porting the HuskyHomes mod for Forge 1.19.2? The developer of this mod agrees, but no one wants to take on this.

**Comment by kitovoi111** [comment]
Mod: https://modrinth.com/plugin/huskhomes

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/Mins-Enchantments/assets/147491823/63386bd0-2c42-4662-bf48-3a1777431eb7)

Official answer developer HuskHomes

**Comment by min2222** [comment]
no
